# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: '3.7'

services:
  greengrass:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aws-iot-greengrass
    image: x86_64/aws-iot-greengrass:2.1.0
    environment:  
      - PROVISION=true
      - DEPLOY_DEV_TOOLS=true
      - THING_NAME=GreengrassQuickStartCore
      - THING_GROUP_NAME=GreengrassQuickStartGroup
    volumes:
      - ~/.aws:/root/.aws/:ro # Pertains to AWS credentials
      - ~/aws-iot-device-sdk-cpp-v2:/root/aws-iot-device-sdk-cpp-v2 # SDK directory
      - ~/gg-ipc-test:/root/ipc-tests # Test directory
      - ~/gg-ipc-uat-recipe:/root/greengrass-components/uat # Recipe directory
      - ~/gg-ipc-uat-recipe/logs:/greengrass/v2/logs